### PR TITLE
Fix for Status buttons on some Linux machines.

### PR DESCRIPTION
**Pull request by ptulp**
Under wxWidgets 3.0.2 the wxButton checks the status of gtk-button-images for GTK machines. 
It looks like for Ubuntu the status is set to not display images on buttons.
On Lubuntu the buttons display correct
I revert back to the old way of displaying the status buttons.

### CODE REVIEW

**Comment by delatbabel** [comment]
Hi Peter,

After merging this I am getting the following build errors:

/home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp: In member function ‘void OverView::loadLogbookData(wxString, bool)’:
/home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:286:29: error: ambiguous overload for ‘operator=’ (operand types are ‘wxString’ and ‘const char [6]’)
                     endtime = "00:00";
                             ^
/home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:286:29: note: candidates are:
In file included from /usr/include/wx-2.8/wx/memory.h:16:0,
                 from /usr/include/wx-2.8/wx/object.h:20,
                 from /usr/include/wx-2.8/wx/wx.h:16,
                 from /home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:3:
/usr/include/wx-2.8/wx/string.h:676:13: note: wxString& wxString::operator=(int) <near match>
   wxString& operator=(int);
             ^
/usr/include/wx-2.8/wx/string.h:676:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘int’
/usr/include/wx-2.8/wx/string.h:956:13: note: wxString& wxString::operator=(wxChar) <near match>
   wxString& operator=(wxChar ch)
             ^
/usr/include/wx-2.8/wx/string.h:956:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:970:13: note: wxString& wxString::operator=(const wxWCharBuffer&) <near match>
   wxString& operator=(const wxWCharBuffer& psz)
             ^
/usr/include/wx-2.8/wx/string.h:970:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:659:24: note: wxString& wxString::operator=(const wxString&) <near match>
 class WXDLLIMPEXP_BASE wxString : public wxStringBase
                        ^
/usr/include/wx-2.8/wx/string.h:659:24: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘const wxString&’
/home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:345:35: error: ambiguous overload for ‘operator=’ (operand types are ‘wxString’ and ‘const char [6]’)
                         starttime = "00:00";
                                   ^
/home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:345:35: note: candidates are:
In file included from /usr/include/wx-2.8/wx/memory.h:16:0,
                 from /usr/include/wx-2.8/wx/object.h:20,
                 from /usr/include/wx-2.8/wx/wx.h:16,
                 from /home/del/github/OpenCPN/plugins/LogbookKonni_pi/src/OverView.cpp:3:
/usr/include/wx-2.8/wx/string.h:676:13: note: wxString& wxString::operator=(int) <near match>
   wxString& operator=(int);
             ^
/usr/include/wx-2.8/wx/string.h:676:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘int’
/usr/include/wx-2.8/wx/string.h:956:13: note: wxString& wxString::operator=(wxChar) <near match>
   wxString& operator=(wxChar ch)
             ^
/usr/include/wx-2.8/wx/string.h:956:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:970:13: note: wxString& wxString::operator=(const wxWCharBuffer&) <near match>
   wxString& operator=(const wxWCharBuffer& psz)
             ^
/usr/include/wx-2.8/wx/string.h:970:13: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:659:24: note: wxString& wxString::operator=(const wxString&) <near match>
 class WXDLLIMPEXP_BASE wxString : public wxStringBase
                        ^
/usr/include/wx-2.8/wx/string.h:659:24: note:   no known conversion for argument 1 from ‘const char [6]’ to ‘const wxString&’
make[2]: *** [CMakeFiles/logbookkonni_pi.dir/src/OverView.cpp.o] Error 1
make[1]: *** [CMakeFiles/logbookkonni_pi.dir/all] Error 2
make: *** [all] Error 2

I note that you refer to wxWidgets 3.0.2 up there but I'm still using 2.8 because that's what I have on Ubuntu. Do I need to update my wxWidgets set or is this still supposed to build on 2.8?

**Comment by ptulp** [comment]
Del,
Since 4.2 all OS'S are using wx3.0.2.
So you have to update to wx3.0.2 for Linux and Windows.

Greetings
Peter

**Comment by delatbabel** [comment]
Hi Peter,
I have drafted a new release. Who is doing the MacOS and Windows builds these days?

**Comment by nohal** [comment]
Del...
I'm catching up slowly with the releases, should get to it by the end of the week.

**Comment by ptulp** [comment]
Pavel,

If you put the releases up on the download page, could you also update the LogbookKonni_Layouts.zip file on the download page?.
I noticed that the LogbookKonni_Layouts.zip on the download page is outdated.

Thanks,
Peter

**Comment by nohal** [comment]
I updated the packages for all the platforms and the layouts from Del's master - hope it is the right branch to use.
